#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

#
# Load .profile for machine-specific configuration
#
if [[ -e "${HOME}/.profile" ]]; then
  source "${HOME}/.profile" 
fi

#
# Disable correction
# 
unsetopt correct
unsetopt correctall
DISABLE_CORRECTION="true"

#
# Change LS color
#
# http://hajimenovic.hatenablog.jp/entry/2015/03/10/204613
export LSCOLORS=gxfxcxdxbxegedabagacad

